<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <UserSecretsId>0488569f-ef1d-4a80-a5c3-48a404f52598</UserSecretsId>
    <Authors>Pieterjan Spoelders</Authors>
    <Company>Exasol AG</Company>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="error-reporting-csharp" Version="0.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="3.12.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />
    <PackageReference Include="morelinq" Version="4.4.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="EXADataProvider.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
